name: Rollback Documentation

on:
  workflow_dispatch:
    inputs:
      rollback_to_version:
        description: 'Documentation version to rollback to (e.g., 1.0.0)'
        required: true
        type: string
      target_branch:
        description: 'Branch to rollback documentation in'
        required: false
        default: 'main'
        type: string
      docs_path:
        description: 'Path to documentation files'
        required: false
        default: '.'
        type: string
      confirm_rollback:
        description: 'Type "CONFIRM" to proceed with rollback'
        required: true
        type: string

jobs:
  rollback-documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Rollback Documentation
        id: rollback
        uses: .github/actions/rollback-docs
        with:
          rollback_to_version: ${{ github.event.inputs.rollback_to_version }}
          target_branch: ${{ github.event.inputs.target_branch }}
          docs_path: ${{ github.event.inputs.docs_path }}
          confirm_rollback: ${{ github.event.inputs.confirm_rollback }}

      - name: Rollback notification
        run: |
          if [ "${{ steps.rollback.outputs.rollback-completed }}" = "true" ]; then
            echo "🔄 **Documentation Rollback Completed**"
            echo ""
            echo "The documentation has been successfully rolled back to version **${{ github.event.inputs.rollback_to_version }}**"
            echo ""
            echo "**Details:**"
            echo "- Version: ${{ github.event.inputs.rollback_to_version }}"
            echo "- Tag: ${{ steps.rollback.outputs.tag-used }}"
            echo "- Branch: ${{ github.event.inputs.target_branch }}"
            echo "- Path: ${{ github.event.inputs.docs_path }}"
            echo "- Files updated: ${{ steps.rollback.outputs.merged-files }}"
            echo "- Commit SHA: ${{ steps.rollback.outputs.commit-sha }}"
            echo "- Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          else
            echo "ℹ️ **No Rollback Needed**"
            echo ""
            echo "The documentation was already at version **${{ github.event.inputs.rollback_to_version }}**"
            echo ""
            echo "**Details:**"
            echo "- Version: ${{ github.event.inputs.rollback_to_version }}"
            echo "- Tag: ${{ steps.rollback.outputs.tag-used }}"
            echo "- Branch: ${{ github.event.inputs.target_branch }}"
            echo "- Latest version: ${{ steps.rollback.outputs.latest-version }}"
          fi
