name: Documentation Versioning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Tag documentation version
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Get the latest documentation tag
          LATEST_TAG=$(git tag -l "documentation-v*" | sort -V | tail -n1)
          
          if [ -z "$LATEST_TAG" ]; then
            # No existing documentation tags, create initial version
            NEW_TAG="documentation-v1.0.0"
            echo "Creating initial documentation tag: $NEW_TAG"
          else
            echo "Latest documentation tag: $LATEST_TAG"
            
            # Extract version numbers (remove 'documentation-v' prefix)
            VERSION=${LATEST_TAG#documentation-v}
            
            # Split version into major.minor.patch
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            
            # Increment patch version (you can modify this logic for major/minor increments)
            PATCH=$((PATCH + 1))
            
            NEW_TAG="documentation-v${MAJOR}.${MINOR}.${PATCH}"
            echo "Creating new documentation tag: $NEW_TAG"
          fi
          
          # Create and push the new tag
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
          
          echo "Successfully created and pushed tag: $NEW_TAG"
