name: Documentation Versioning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      version_increment:
        description: 'Version increment strategy'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    
    outputs:
      version-tag: ${{ steps.tag-version.outputs.tag }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Tag documentation version
        id: tag-version
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Get version increment strategy (default to patch for push events)
          VERSION_INCREMENT="${{ github.event.inputs.version_increment || 'patch' }}"
          echo "Version increment strategy: $VERSION_INCREMENT"
          
          # Get the latest documentation tag
          LATEST_TAG=$(git tag -l "documentation-v*" | sort -V | tail -n1)
          
          if [ -z "$LATEST_TAG" ]; then
            # No existing documentation tags, create initial version
            NEW_TAG="documentation-v1.0.0"
            echo "Creating initial documentation tag: $NEW_TAG"
          else
            echo "Latest documentation tag: $LATEST_TAG"
            
            # Extract version numbers (remove 'documentation-v' prefix)
            VERSION=${LATEST_TAG#documentation-v}
            
            # Split version into major.minor.patch
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            
            # Increment version based on strategy
            case $VERSION_INCREMENT in
              major)
                MAJOR=$((MAJOR + 1))
                MINOR=0
                PATCH=0
                echo "Incrementing major version"
                ;;
              minor)
                MINOR=$((MINOR + 1))
                PATCH=0
                echo "Incrementing minor version"
                ;;
              patch)
                PATCH=$((PATCH + 1))
                echo "Incrementing patch version"
                ;;
              *)
                echo "Invalid version increment strategy: $VERSION_INCREMENT. Using patch."
                PATCH=$((PATCH + 1))
                ;;
            esac
            
            NEW_TAG="documentation-v${MAJOR}.${MINOR}.${PATCH}"
            echo "Creating new documentation tag: $NEW_TAG"
          fi
          
          # Create and push the new tag
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
          
          echo "Successfully created and pushed tag: $NEW_TAG"
          echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT

  release:
    needs: build
    runs-on: ubuntu-latest
    name: "Release ${{ needs.build.outputs.version-tag }}"
    
    steps:
      - name: Display version
        run: echo "Building release for version ${{ needs.build.outputs.version-tag }}"
